version: '3.8'

services:
  chef_proxy:
    build: .
    image: tor-app:latest
    ports:
      - "8080:8080"
    environment:
      - ROLE=CHEF
      - CONTAINER_NAME=chef_proxy
      - REGISTRY_URL=http://registre:8090
    networks:
      - tor-network

  registre:
    image: tor-app:latest
    ports:
      - "8090:8090"
    environment:
      - ROLE=REGISTRE
      - SERVER_PORT=8090
    networks:
      - tor-network

networks:
  tor-network:
    name: tor-network